version: 1
directus: 11.14.0
vendor: postgres
collections:
  - collection: ai_prompts
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: ai_prompts
      color: null
      display_template: null
      group: null
      hidden: false
      icon: magic_button
      item_duplication_fields: null
      note: null
      preview_url: null
      singleton: false
      sort: null
      sort_field: sort
      translations: null
      unarchive_value: draft
      versioning: false
    schema:
      name: ai_prompts
fields:
  - collection: ai_prompts
    field: id
    type: uuid
    meta:
      collection: ai_prompts
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: id
      table: ai_prompts
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_indexed: false
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: ai_prompts
    field: sort
    type: integer
    meta:
      collection: ai_prompts
      conditions: null
      display: null
      display_options: null
      field: sort
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: sort
      table: ai_prompts
      data_type: integer
      default_value: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: ai_prompts
    field: date_created
    type: timestamp
    meta:
      collection: ai_prompts
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_created
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      searchable: true
      sort: 3
      special:
        - date-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_created
      table: ai_prompts
      data_type: timestamp with time zone
      default_value: CURRENT_TIMESTAMP
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: ai_prompts
    field: user_created
    type: uuid
    meta:
      collection: ai_prompts
      conditions: null
      display: user
      display_options: null
      field: user_created
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      searchable: true
      sort: 4
      special:
        - user-created
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_created
      table: ai_prompts
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: ai_prompts
    field: date_updated
    type: timestamp
    meta:
      collection: ai_prompts
      conditions: null
      display: datetime
      display_options:
        relative: true
      field: date_updated
      group: null
      hidden: true
      interface: datetime
      note: null
      options: null
      readonly: true
      required: false
      searchable: true
      sort: 5
      special:
        - date-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date_updated
      table: ai_prompts
      data_type: timestamp with time zone
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: ai_prompts
    field: user_updated
    type: uuid
    meta:
      collection: ai_prompts
      conditions: null
      display: user
      display_options: null
      field: user_updated
      group: null
      hidden: true
      interface: select-dropdown-m2o
      note: null
      options:
        template: '{{avatar}} {{first_name}} {{last_name}}'
      readonly: true
      required: false
      searchable: true
      sort: 6
      special:
        - user-updated
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: user_updated
      table: ai_prompts
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: directus_users
      foreign_key_column: id
  - collection: ai_prompts
    field: meta_prompts_notice
    type: alias
    meta:
      collection: ai_prompts
      conditions: null
      display: null
      display_options: null
      field: meta_prompts_notice
      group: null
      hidden: false
      interface: presentation-notice
      note: null
      options:
        icon: info
        text: $t:mcp_prompts_collection_schema.meta_prompts_notice
      readonly: false
      required: false
      searchable: true
      sort: 7
      special:
        - alias
        - no-data
      translations: null
      validation: null
      validation_message: null
      width: full
  - collection: ai_prompts
    field: name
    type: string
    meta:
      collection: ai_prompts
      conditions: null
      display: formatted-value
      display_options:
        font: monospace
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options:
        slug: true
        trim: true
      readonly: false
      required: true
      searchable: true
      sort: 8
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: name
      table: ai_prompts
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: true
      is_indexed: true
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: ai_prompts
    field: status
    type: string
    meta:
      collection: ai_prompts
      conditions: null
      display: labels
      display_options:
        choices:
          - background: var(--theme--primary-background)
            color: var(--theme--primary)
            foreground: var(--theme--primary)
            text: $t:published
            value: published
          - background: var(--theme--background-normal)
            color: var(--theme--foreground)
            foreground: var(--theme--foreground)
            text: $t:draft
            value: draft
          - background: var(--theme--warning-background)
            color: var(--theme--warning)
            foreground: var(--theme--warning)
            text: $t:archived
            value: archived
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - color: var(--theme--primary)
            text: $t:published
            value: published
          - color: var(--theme--foreground)
            text: $t:draft
            value: draft
          - color: var(--theme--warning)
            text: $t:archived
            value: archived
      readonly: false
      required: false
      searchable: true
      sort: 9
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: status
      table: ai_prompts
      data_type: character varying
      default_value: draft
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: ai_prompts
    field: description
    type: text
    meta:
      collection: ai_prompts
      conditions: null
      display: null
      display_options: null
      field: description
      group: null
      hidden: false
      interface: input
      note: null
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 10
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: description
      table: ai_prompts
      data_type: text
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: ai_prompts
    field: system_prompt
    type: text
    meta:
      collection: ai_prompts
      conditions: null
      display: null
      display_options: null
      field: system_prompt
      group: null
      hidden: false
      interface: input-rich-text-md
      note: $t:mcp_prompts_collection_schema.system_prompt_note
      options: null
      readonly: false
      required: false
      searchable: true
      sort: 11
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: system_prompt
      table: ai_prompts
      data_type: text
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: ai_prompts
    field: messages
    type: json
    meta:
      collection: ai_prompts
      conditions: null
      display: formatted-json-value
      display_options:
        format: '{{ role }} • {{ text }}'
      field: messages
      group: null
      hidden: false
      interface: list
      note: $t:mcp_prompts_collection_schema.messages_note
      options:
        addLabel: New Message
        fields:
          - field: role
            meta:
              display: labels
              display_options:
                choices:
                  - icon: person
                    text: $t:mcp_prompts_collection_schema.messages_role_user
                    value: user
                  - icon: smart_toy
                    text: $t:mcp_prompts_collection_schema.messages_role_assistant
                    value: assistant
              field: role
              interface: select-dropdown
              note: $t:mcp_prompts_collection_schema.messages_role_note
              options:
                choices:
                  - icon: person
                    text: $t:mcp_prompts_collection_schema.messages_role_user
                    value: user
                  - icon: smart_toy
                    text: $t:mcp_prompts_collection_schema.messages_role_assistant
                    value: assistant
              required: true
              type: string
              width: full
            name: role
            type: string
          - field: text
            meta:
              display: formatted-value
              display_options:
                format: true
              field: text
              interface: input-rich-text-md
              note: >-
                The actual content of the message. You can use {{ curly_braces
                }} for placeholders that will be replaced with real data.
              required: true
              type: text
              width: full
            name: text
            type: text
        showConfirmDiscard: true
        template: '{{ role }} • {{ text }}'
      readonly: false
      required: false
      searchable: true
      sort: 12
      special:
        - cast-json
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: messages
      table: ai_prompts
      data_type: json
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_indexed: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
systemFields:
  - collection: directus_activity
    field: timestamp
    schema:
      is_indexed: true
  - collection: directus_revisions
    field: parent
    schema:
      is_indexed: true
relations:
  - collection: ai_prompts
    field: user_updated
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: ai_prompts
      many_field: user_updated
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: ai_prompts
      column: user_updated
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: ai_prompts_user_updated_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
  - collection: ai_prompts
    field: user_created
    related_collection: directus_users
    meta:
      junction_field: null
      many_collection: ai_prompts
      many_field: user_created
      one_allowed_collections: null
      one_collection: directus_users
      one_collection_field: null
      one_deselect_action: nullify
      one_field: null
      sort_field: null
    schema:
      table: ai_prompts
      column: user_created
      foreign_key_table: directus_users
      foreign_key_column: id
      constraint_name: ai_prompts_user_created_foreign
      on_update: NO ACTION
      on_delete: NO ACTION
